name: 'cryptoshark'

services:
  db:
    image: postgres:18
    restart: unless-stopped
    env_file: 
      - .env
    ports:
      - "$POSTGRES_PORT:5432"
    volumes:
      - ./data/app_postgres:/var/lib/postgresql
    networks:
      - default
  
  redis:
    image: redis:8-alpine
    restart: unless-stopped
    command: "redis-server --save 60 1 --appendonly yes --appendfsync everysec"
    env_file:
      - .env
    ports:
      - "$REDIS_PORT:6379"
    volumes:
      - ./data/app_redis:/data
    networks:
      - default

networks:
  default:
    driver: bridge
