"""database_initialization

Revision ID: 4dc2110ffdea
Revises:
Create Date: 2026-01-28 18:41:21.220130

"""

from typing import Sequence, Union

import pgvector
import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4dc2110ffdea"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade(engine_name: str) -> None:
    """Upgrade schema."""
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name: str) -> None:
    """Downgrade schema."""
    globals()["downgrade_%s" % engine_name]()


def upgrade_main() -> None:
    """Upgrade main schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_config",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("value", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key"),
    )
    op.create_table(
        "klines_12h",
        sa.Column("ticker", sa.String(), nullable=False),
        sa.Column("open_time", sa.BigInteger(), nullable=False),
        sa.Column("open", sa.Float(), nullable=False),
        sa.Column("high", sa.Float(), nullable=False),
        sa.Column("low", sa.Float(), nullable=False),
        sa.Column("close", sa.Float(), nullable=False),
        sa.Column("base_asset_volume", sa.Float(), nullable=False),
        sa.Column("close_time", sa.BigInteger(), nullable=False),
        sa.Column("quote_asset_volume", sa.Float(), nullable=False),
        sa.Column("number_of_trades", sa.Integer(), nullable=False),
        sa.Column("taker_buy_base_asset_volume", sa.Float(), nullable=False),
        sa.Column("taker_buy_quote_asset_volume", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("ticker", "open_time"),
    )
    op.create_table(
        "klines_15m",
        sa.Column("ticker", sa.String(), nullable=False),
        sa.Column("open_time", sa.BigInteger(), nullable=False),
        sa.Column("open", sa.Float(), nullable=False),
        sa.Column("high", sa.Float(), nullable=False),
        sa.Column("low", sa.Float(), nullable=False),
        sa.Column("close", sa.Float(), nullable=False),
        sa.Column("base_asset_volume", sa.Float(), nullable=False),
        sa.Column("close_time", sa.BigInteger(), nullable=False),
        sa.Column("quote_asset_volume", sa.Float(), nullable=False),
        sa.Column("number_of_trades", sa.Integer(), nullable=False),
        sa.Column("taker_buy_base_asset_volume", sa.Float(), nullable=False),
        sa.Column("taker_buy_quote_asset_volume", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("ticker", "open_time"),
    )
    op.create_table(
        "klines_1d",
        sa.Column("ticker", sa.String(), nullable=False),
        sa.Column("open_time", sa.BigInteger(), nullable=False),
        sa.Column("open", sa.Float(), nullable=False),
        sa.Column("high", sa.Float(), nullable=False),
        sa.Column("low", sa.Float(), nullable=False),
        sa.Column("close", sa.Float(), nullable=False),
        sa.Column("base_asset_volume", sa.Float(), nullable=False),
        sa.Column("close_time", sa.BigInteger(), nullable=False),
        sa.Column("quote_asset_volume", sa.Float(), nullable=False),
        sa.Column("number_of_trades", sa.Integer(), nullable=False),
        sa.Column("taker_buy_base_asset_volume", sa.Float(), nullable=False),
        sa.Column("taker_buy_quote_asset_volume", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("ticker", "open_time"),
    )
    op.create_table(
        "klines_1h",
        sa.Column("ticker", sa.String(), nullable=False),
        sa.Column("open_time", sa.BigInteger(), nullable=False),
        sa.Column("open", sa.Float(), nullable=False),
        sa.Column("high", sa.Float(), nullable=False),
        sa.Column("low", sa.Float(), nullable=False),
        sa.Column("close", sa.Float(), nullable=False),
        sa.Column("base_asset_volume", sa.Float(), nullable=False),
        sa.Column("close_time", sa.BigInteger(), nullable=False),
        sa.Column("quote_asset_volume", sa.Float(), nullable=False),
        sa.Column("number_of_trades", sa.Integer(), nullable=False),
        sa.Column("taker_buy_base_asset_volume", sa.Float(), nullable=False),
        sa.Column("taker_buy_quote_asset_volume", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("ticker", "open_time"),
    )
    op.create_table(
        "klines_1m",
        sa.Column("ticker", sa.String(), nullable=False),
        sa.Column("open_time", sa.BigInteger(), nullable=False),
        sa.Column("open", sa.Float(), nullable=False),
        sa.Column("high", sa.Float(), nullable=False),
        sa.Column("low", sa.Float(), nullable=False),
        sa.Column("close", sa.Float(), nullable=False),
        sa.Column("base_asset_volume", sa.Float(), nullable=False),
        sa.Column("close_time", sa.BigInteger(), nullable=False),
        sa.Column("quote_asset_volume", sa.Float(), nullable=False),
        sa.Column("number_of_trades", sa.Integer(), nullable=False),
        sa.Column("taker_buy_base_asset_volume", sa.Float(), nullable=False),
        sa.Column("taker_buy_quote_asset_volume", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("ticker", "open_time"),
    )
    op.create_table(
        "klines_1s",
        sa.Column("ticker", sa.String(), nullable=False),
        sa.Column("open_time", sa.BigInteger(), nullable=False),
        sa.Column("open", sa.Float(), nullable=False),
        sa.Column("high", sa.Float(), nullable=False),
        sa.Column("low", sa.Float(), nullable=False),
        sa.Column("close", sa.Float(), nullable=False),
        sa.Column("base_asset_volume", sa.Float(), nullable=False),
        sa.Column("close_time", sa.BigInteger(), nullable=False),
        sa.Column("quote_asset_volume", sa.Float(), nullable=False),
        sa.Column("number_of_trades", sa.Integer(), nullable=False),
        sa.Column("taker_buy_base_asset_volume", sa.Float(), nullable=False),
        sa.Column("taker_buy_quote_asset_volume", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("ticker", "open_time"),
    )
    op.create_table(
        "klines_2h",
        sa.Column("ticker", sa.String(), nullable=False),
        sa.Column("open_time", sa.BigInteger(), nullable=False),
        sa.Column("open", sa.Float(), nullable=False),
        sa.Column("high", sa.Float(), nullable=False),
        sa.Column("low", sa.Float(), nullable=False),
        sa.Column("close", sa.Float(), nullable=False),
        sa.Column("base_asset_volume", sa.Float(), nullable=False),
        sa.Column("close_time", sa.BigInteger(), nullable=False),
        sa.Column("quote_asset_volume", sa.Float(), nullable=False),
        sa.Column("number_of_trades", sa.Integer(), nullable=False),
        sa.Column("taker_buy_base_asset_volume", sa.Float(), nullable=False),
        sa.Column("taker_buy_quote_asset_volume", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("ticker", "open_time"),
    )
    op.create_table(
        "klines_30m",
        sa.Column("ticker", sa.String(), nullable=False),
        sa.Column("open_time", sa.BigInteger(), nullable=False),
        sa.Column("open", sa.Float(), nullable=False),
        sa.Column("high", sa.Float(), nullable=False),
        sa.Column("low", sa.Float(), nullable=False),
        sa.Column("close", sa.Float(), nullable=False),
        sa.Column("base_asset_volume", sa.Float(), nullable=False),
        sa.Column("close_time", sa.BigInteger(), nullable=False),
        sa.Column("quote_asset_volume", sa.Float(), nullable=False),
        sa.Column("number_of_trades", sa.Integer(), nullable=False),
        sa.Column("taker_buy_base_asset_volume", sa.Float(), nullable=False),
        sa.Column("taker_buy_quote_asset_volume", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("ticker", "open_time"),
    )
    op.create_table(
        "klines_3m",
        sa.Column("ticker", sa.String(), nullable=False),
        sa.Column("open_time", sa.BigInteger(), nullable=False),
        sa.Column("open", sa.Float(), nullable=False),
        sa.Column("high", sa.Float(), nullable=False),
        sa.Column("low", sa.Float(), nullable=False),
        sa.Column("close", sa.Float(), nullable=False),
        sa.Column("base_asset_volume", sa.Float(), nullable=False),
        sa.Column("close_time", sa.BigInteger(), nullable=False),
        sa.Column("quote_asset_volume", sa.Float(), nullable=False),
        sa.Column("number_of_trades", sa.Integer(), nullable=False),
        sa.Column("taker_buy_base_asset_volume", sa.Float(), nullable=False),
        sa.Column("taker_buy_quote_asset_volume", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("ticker", "open_time"),
    )
    op.create_table(
        "klines_4h",
        sa.Column("ticker", sa.String(), nullable=False),
        sa.Column("open_time", sa.BigInteger(), nullable=False),
        sa.Column("open", sa.Float(), nullable=False),
        sa.Column("high", sa.Float(), nullable=False),
        sa.Column("low", sa.Float(), nullable=False),
        sa.Column("close", sa.Float(), nullable=False),
        sa.Column("base_asset_volume", sa.Float(), nullable=False),
        sa.Column("close_time", sa.BigInteger(), nullable=False),
        sa.Column("quote_asset_volume", sa.Float(), nullable=False),
        sa.Column("number_of_trades", sa.Integer(), nullable=False),
        sa.Column("taker_buy_base_asset_volume", sa.Float(), nullable=False),
        sa.Column("taker_buy_quote_asset_volume", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("ticker", "open_time"),
    )
    op.create_table(
        "klines_5m",
        sa.Column("ticker", sa.String(), nullable=False),
        sa.Column("open_time", sa.BigInteger(), nullable=False),
        sa.Column("open", sa.Float(), nullable=False),
        sa.Column("high", sa.Float(), nullable=False),
        sa.Column("low", sa.Float(), nullable=False),
        sa.Column("close", sa.Float(), nullable=False),
        sa.Column("base_asset_volume", sa.Float(), nullable=False),
        sa.Column("close_time", sa.BigInteger(), nullable=False),
        sa.Column("quote_asset_volume", sa.Float(), nullable=False),
        sa.Column("number_of_trades", sa.Integer(), nullable=False),
        sa.Column("taker_buy_base_asset_volume", sa.Float(), nullable=False),
        sa.Column("taker_buy_quote_asset_volume", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("ticker", "open_time"),
    )
    op.create_table(
        "klines_6h",
        sa.Column("ticker", sa.String(), nullable=False),
        sa.Column("open_time", sa.BigInteger(), nullable=False),
        sa.Column("open", sa.Float(), nullable=False),
        sa.Column("high", sa.Float(), nullable=False),
        sa.Column("low", sa.Float(), nullable=False),
        sa.Column("close", sa.Float(), nullable=False),
        sa.Column("base_asset_volume", sa.Float(), nullable=False),
        sa.Column("close_time", sa.BigInteger(), nullable=False),
        sa.Column("quote_asset_volume", sa.Float(), nullable=False),
        sa.Column("number_of_trades", sa.Integer(), nullable=False),
        sa.Column("taker_buy_base_asset_volume", sa.Float(), nullable=False),
        sa.Column("taker_buy_quote_asset_volume", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("ticker", "open_time"),
    )
    op.create_table(
        "klines_8h",
        sa.Column("ticker", sa.String(), nullable=False),
        sa.Column("open_time", sa.BigInteger(), nullable=False),
        sa.Column("open", sa.Float(), nullable=False),
        sa.Column("high", sa.Float(), nullable=False),
        sa.Column("low", sa.Float(), nullable=False),
        sa.Column("close", sa.Float(), nullable=False),
        sa.Column("base_asset_volume", sa.Float(), nullable=False),
        sa.Column("close_time", sa.BigInteger(), nullable=False),
        sa.Column("quote_asset_volume", sa.Float(), nullable=False),
        sa.Column("number_of_trades", sa.Integer(), nullable=False),
        sa.Column("taker_buy_base_asset_volume", sa.Float(), nullable=False),
        sa.Column("taker_buy_quote_asset_volume", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("ticker", "open_time"),
    )
    # ### end Alembic commands ###


def downgrade_main() -> None:
    """Downgrade main schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("klines_8h")
    op.drop_table("klines_6h")
    op.drop_table("klines_5m")
    op.drop_table("klines_4h")
    op.drop_table("klines_3m")
    op.drop_table("klines_30m")
    op.drop_table("klines_2h")
    op.drop_table("klines_1s")
    op.drop_table("klines_1m")
    op.drop_table("klines_1h")
    op.drop_table("klines_1d")
    op.drop_table("klines_15m")
    op.drop_table("klines_12h")
    op.drop_table("app_config")
    # ### end Alembic commands ###


def upgrade_vector() -> None:
    """Upgrade vector schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table(
        "knowledge_base",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade_vector() -> None:
    """Downgrade vector schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("knowledge_base")
    # ### end Alembic commands ###
